import './styles/globals.scss';
import Providers from './theme-provider';
import { Desktop } from './components/desktop';
import type { Metadata } from 'next'


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <>
    <Providers>
        <html lang="en">
          <body>
            <Desktop></Desktop>
            {children}
          </body>
        </html>
      </Providers>
    </>
  )
}
